### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by MrLongDeng** [fallenner/bookshop#6]
运行不起来项目，没有入口啊，怎么运行呢

**Comment by fallenner** [comment]
@MrLongDeng  是不会用maven吗。

**Comment by MrLongDeng** [comment]
maven的什么命令呢

**Comment by MrLongDeng** [comment]
我打包了，运行war失败了

**Comment by fallenner** [comment]
用IDEA 配置好tomcat 直接运行就可以了吧。 你是用什么方式运行的，报的什么错？

**Comment by fallenner** [comment]
@MrLongDeng  我试了用IDEA配置tomcat启动，没有问题

**Comment by changhe626** [comment]
获取不到${baseUrl} 这个错误

**Comment by InJamie** [comment]
可以正常运行，感谢作者可以做学习参考。

**Comment by fallenner** [comment]
@MrLongDeng  如下图，你的context 不要设置成 / ，这是个bug，现在在重构2.0版本，所以暂时不会改了。
![image](https://user-images.githubusercontent.com/22296628/78334074-aeca8c80-75bd-11ea-9f0f-b13c155be8c9.png)
